workflows:
  ios-testflight:
    name: "iOS TestFlight Build"
    max_build_duration: 60
    environment:
      groups:
        - ios-credentials   # Burada senin belirlediğin grup adı olmalı
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
    scripts:
      - name: 📦 Clean and Install Pods
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..
      - name: 🔐 Decode and Configure Signing
        script: |
          echo "Apple ID: $APPLE_ID"
          echo "Setting up signing..."
      - name: 🛠️ Build iOS
        script: |
          flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        issuer_id: $APP_STORE_ISSUER_ID
        api_key: $APP_STORE_API_KEY
        submit_to_testflight: true
        submit_to_app_store: false
