workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Pre-build checks
        script: |
          if [ ! -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "❌ GoogleService-Info.plist missing!"
            exit 1
          fi
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..
    artifacts:
      - build/ios/ipa/*.ipa
