workflows:
  ios-testflight:
    name: "iOS TestFlight Build"
    max_build_duration: 60
    environment:
      groups:
        - ios-credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Decode P12 and save to file
        script: |
          echo $CERTIFICATE_P12 | base64 --decode > ios_distribution.p12
      - name: Set up keychain and import certificate
        script: |
          security create-keychain -p "" build.keychain
          security import ios_distribution.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -d user -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
